# Generated by Django 4.1.1 on 2022-10-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_tomeet_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tomeet',
            name='comment',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='tomeet',
            name='phone_number',
            field=models.IntegerField(default=True),
        ),
    ]
